# 头部菜单，title: link
menu:
  Whoami: https://github.com/l4503071/blog
  Github: https://github.com/l4503071

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - /audio/audio_1.mp3
  - /audio/audio_2.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '3da866a97761a8813fe9'
    # 应用秘钥
    clientSecret: '10fae746c495bdbb97f24acb1cf9d13f072673bd'
    # issue仓库名
    repo: 'blog'
    # Github名
    owner: 'l4503071'
    # Github名
    admin: ['l4503071']
    # Ensure uniqueness and length less than 50
    id: sunshine
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: sunshine

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml

# 配置是否显示背景图
canvas_nest: true
